# Generated by Django 4.2.2 on 2024-07-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycolor', '0002_alter_otp_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_code',
            field=models.CharField(default='7af4eb', max_length=6),
        ),
    ]
