# Generated by Django 4.2.2 on 2024-07-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycolor', '0003_alter_otp_otp_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='tp_created_at',
            new_name='otp_created_at',
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_code',
            field=models.CharField(default='491ba7', max_length=6),
        ),
    ]
