# Generated by Django 4.2.2 on 2024-07-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycolor', '0004_rename_tp_created_at_otp_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_code',
            field=models.CharField(default='6fd76b', max_length=6),
        ),
    ]
