# Generated by Django 4.2.2 on 2024-07-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycolor', '0006_alter_otp_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_code',
            field=models.CharField(default='35a17a', max_length=6),
        ),
    ]
