# Generated by Django 4.2.2 on 2024-08-24 10:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("mycolor", "0009_alter_otp_otp_code_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="otp",
            name="otp_code",
            field=models.CharField(default="b4ce35", max_length=6),
        ),
    ]
